-- Tiered seed policies: open / standard / governed.
-- Design: docs/superpowers/specs/2026-08-11-tiered-policies-design.md
--
-- BACKFILL ONLY. `policies/*.yaml` is the source of truth, and the boot seeder
-- (fluidbox_db::seed::run) covers every FRESH deployment. This file exists for
-- databases that already exist and will never run a fresh seed for a non-boot
-- tenant. The two must agree, and `migration_0029_jsonb_matches_the_yaml` in
-- fluidbox-core asserts the jsonb below equals the parsed YAML — the jsonb here
-- was GENERATED by serializing those documents, never hand-written.
--
-- WHY THE BYPASS: a migration connection carries NO tenant GUC, and `policies`
-- is ENABLE+FORCE RLS keyed on current_setting('fluidbox.tenant_id'). Without
-- the audited system-worker bypass the insert below reads and writes ZERO rows
-- -- silently. That is an empty backfill, not an error, which is the failure
-- mode worth the one line. Transaction-local by construction: sqlx runs each
-- migration file in a single transaction.
set local fluidbox.bypass = 'system_worker';

-- ADDITIVE: creates rows, drops nothing, alters no column, so unlike 0018/0026
-- an older binary can serve beside it -- it simply sees extra rows in tables it
-- already understands.
--
-- ONE RESIDUAL, disclosed rather than smoothed over: under RollingUpdate (which
-- server.archiveStore=s3 selects) an OLD pod can create an org in the window
-- after this migration has run and been recorded. Old code does not seed
-- policies, this migration never reruns, and retrying the slug returns 409 --
-- so that org is left with none. Deployments on the Recreate strategy (the
-- default, and eks) cannot hit it. Repair is a re-seed of that tenant, never an
-- edit to this file: sqlx checksums an applied migration.
--
-- `default` and any pre-existing policy of these names are NEVER touched: the
-- ON CONFLICT makes the insert a no-op, and only rows this migration actually
-- CREATED come back through `created`, so only they get a version row.
with tiers(name, content) as (
  values
    ('open', '{"name":"open","defaults":{"tool_action":"allow"},"egress":{"mode":"proxy-only"},"network":{"max_mode":"public","allow":[],"deny":[],"require_approval":false,"allow_public_with_brokered":true,"max_grant_secs":null},"budgets":{"max_wall_clock_secs":7200,"max_tokens":null,"max_cost_usd":25.0,"max_tool_calls":null},"approvals":{"default_ttl_secs":600,"scope":"session","timeout_action":"deny"},"autonomy":{"permitted":true,"on_approval_rule":"allow"},"tools":[]}'::jsonb),
    ('standard', '{"name":"standard","defaults":{"tool_action":"approve"},"egress":{"mode":"proxy-only"},"network":{"max_mode":"approved","allow":[],"deny":[],"require_approval":true,"allow_public_with_brokered":false,"max_grant_secs":null},"budgets":{"max_wall_clock_secs":3600,"max_tokens":2000000,"max_cost_usd":5.0,"max_tool_calls":200},"approvals":{"default_ttl_secs":600,"scope":"once","timeout_action":"deny"},"autonomy":{"permitted":true,"on_approval_rule":"deny"},"tools":[{"match":["Read","Glob","Grep","LS","TodoWrite","NotebookRead","ToolSearch","EnterPlanMode","ExitPlanMode","AskUserQuestion","ReportFindings","TaskGet","TaskList","TaskOutput","CronList"],"action":"allow","risk":null,"paths":null,"shell":null,"on_autonomous":null,"approval_ttl_secs":null,"approval_scope":null},{"match":["Agent","Task","Workflow","Skill","TaskCreate"],"action":"deny","risk":"spawns sub-execution whose nested tool calls the gate may never see","paths":null,"shell":null,"on_autonomous":null,"approval_ttl_secs":null,"approval_scope":null},{"match":["Edit","Write","MultiEdit","NotebookEdit"],"action":"allow","risk":null,"paths":{"allow":["/workspace/**"],"deny":["**/.env","**/.env.*","**/.git/config","**/.git/hooks/**"]},"shell":null,"on_autonomous":null,"approval_ttl_secs":null,"approval_scope":null},{"match":["Bash","BashOutput","KillShell"],"action":"allow","risk":null,"paths":null,"shell":{"allow_prefixes":["ls","cat","head","tail","wc","grep","rg","find","pwd","echo","which","env | grep","python","python3","pytest","pip install -r","node","npm test","npm run test","npx jest","npx vitest","cargo test","cargo build","cargo check","go test","make test","git status","git diff","git log","git add","git commit","git show","cd","mkdir","touch","mv","cp","sed","awk","diff","sort","uniq","cut","tr","stat","file","du","printf","basename","dirname","date"],"deny_regex":["rm\\s+(-[a-z]+\\s+)*-[a-z]*r[a-z]*(\\s+-[a-z]+)*\\s+/\\*?(\\s|$)","\\bcurl\\b","\\bwget\\b","\\bnc\\b","\\bssh\\b","\\bscp\\b","git\\s+push\\b.*\\s(--force(-with-lease)?|-f)\\b","\\bsudo\\b","/etc/passwd","\\bchmod\\s+777\\b"],"on_no_match":"approve"},"on_autonomous":null,"approval_ttl_secs":null,"approval_scope":null},{"match":["WebFetch","WebSearch","DesignSync","Monitor"],"action":"deny","risk":"network egress from sandbox","paths":null,"shell":null,"on_autonomous":null,"approval_ttl_secs":null,"approval_scope":null},{"match":["TaskStop","TaskUpdate","SendMessage","CronCreate","CronDelete","ScheduleWakeup","PushNotification","EnterWorktree","ExitWorktree"],"action":"approve","risk":"effect outside this run''s disposable workspace","paths":null,"shell":null,"on_autonomous":null,"approval_ttl_secs":null,"approval_scope":null},{"match":["mcp__*"],"action":"approve","risk":"unreviewed MCP tool","paths":null,"shell":null,"on_autonomous":null,"approval_ttl_secs":null,"approval_scope":null}]}'::jsonb),
    ('governed', '{"name":"governed","defaults":{"tool_action":"deny"},"egress":{"mode":"proxy-only"},"budgets":{"max_wall_clock_secs":900,"max_tokens":300000,"max_cost_usd":1.0,"max_tool_calls":40},"approvals":{"default_ttl_secs":300,"scope":"once","timeout_action":"deny"},"autonomy":{"permitted":false,"on_approval_rule":"deny"},"tools":[{"match":["Read","Glob","Grep","LS","TodoWrite","NotebookRead","EnterPlanMode","ExitPlanMode","AskUserQuestion"],"action":"allow","risk":null,"paths":null,"shell":null,"on_autonomous":null,"approval_ttl_secs":null,"approval_scope":null},{"match":["Edit","Write","MultiEdit","NotebookEdit"],"action":"approve","risk":"writes require a human under the governed tier","paths":{"allow":["/workspace/**"],"deny":["**/.env","**/.env.*","**/.git/config","**/.git/hooks/**"]},"shell":null,"on_autonomous":null,"approval_ttl_secs":null,"approval_scope":null},{"match":["Bash","BashOutput","KillShell"],"action":"allow","risk":null,"paths":null,"shell":{"allow_prefixes":["ls","cat","head","tail","wc","grep","rg","find","pwd","git status","git diff","git log"],"deny_regex":["[;&|]","[<>]","\\$\\(","`","-delete","-exec","-execdir","-fprint","-fls","\\brm\\b","\\bdd\\b","\\bmv\\b","\\btee\\b","\\btruncate\\b","\\bchmod\\b","\\bchown\\b","\\bcurl\\b","\\bwget\\b","\\bnc\\b","\\bssh\\b","\\bscp\\b","\\bsudo\\b","/etc/passwd"],"on_no_match":"deny"},"on_autonomous":null,"approval_ttl_secs":null,"approval_scope":null},{"match":["mcp__*"],"action":"approve","risk":"unreviewed MCP tool","paths":null,"shell":null,"on_autonomous":null,"approval_ttl_secs":null,"approval_scope":null}]}'::jsonb)
),
created as (
  insert into policies (id, tenant_id, name)
  select gen_random_uuid(), t.id, tiers.name
    from tenants t cross join tiers
  on conflict (tenant_id, name) do nothing
  returning id, tenant_id, name
)
insert into policy_versions
  (id, tenant_id, policy_id, version, content, yaml_source, summary, author)
select gen_random_uuid(), c.tenant_id, c.id, 1, tiers.content, null,
       'seeded tier: ' || c.name, 'seed'
  from created c join tiers on tiers.name = c.name;
