-- Tiered seed policies: open / standard / governed.
-- Design: docs/superpowers/specs/2026-08-11-tiered-policies-design.md
--
-- BACKFILL ONLY. `policies/*.yaml` is the source of truth, and the boot seeder
-- (fluidbox_db::seed::run) covers every FRESH deployment. This file exists for
-- databases that already exist and will never run a fresh seed for a non-boot
-- tenant. The two must agree, and `migration_0029_jsonb_matches_the_yaml` in
-- fluidbox-core asserts the jsonb below equals the parsed YAML — the jsonb here
-- was GENERATED by serializing those documents, never hand-written.
--
-- WHY THE BYPASS: a migration connection carries NO tenant GUC, and `policies`
-- is ENABLE+FORCE RLS keyed on current_setting('fluidbox.tenant_id'). Without
-- the audited system-worker bypass the insert below reads and writes ZERO rows
-- -- silently. That is an empty backfill, not an error, which is the failure
-- mode worth the one line. Transaction-local by construction: sqlx runs each
-- migration file in a single transaction.
set local fluidbox.bypass = 'system_worker';

-- ADDITIVE: creates rows, drops nothing, alters no column. Unlike 0018/0026
-- this needs NO stop-the-old-binary posture -- an older binary simply sees
-- extra rows in tables it already understands. Normal rolling deploy.
--
-- `default` and any pre-existing policy of these names are NEVER touched: the
-- ON CONFLICT makes the insert a no-op, and only rows this migration actually
-- CREATED come back through `created`, so only they get a version row.
with tiers(name, content) as (
  values
    ('open', '{"name": "open", "tools": [], "egress": {"mode": "proxy-only"}, "budgets": {"max_tokens": null, "max_cost_usd": 25.0, "max_tool_calls": null, "max_wall_clock_secs": 7200}, "network": {"deny": [], "allow": [], "max_mode": "public", "max_grant_secs": null, "require_approval": false, "allow_public_with_brokered": true}, "autonomy": {"permitted": true, "on_approval_rule": "allow"}, "defaults": {"tool_action": "allow"}, "approvals": {"scope": "session", "timeout_action": "deny", "default_ttl_secs": 600}}'::jsonb),
    ('standard', '{"name": "standard", "tools": [{"risk": null, "match": ["Read", "Glob", "Grep", "LS", "TodoWrite", "NotebookRead", "ToolSearch", "EnterPlanMode", "ExitPlanMode", "AskUserQuestion", "ReportFindings", "TaskGet", "TaskList", "TaskOutput", "CronList"], "paths": null, "shell": null, "action": "allow", "on_autonomous": null, "approval_scope": null, "approval_ttl_secs": null}, {"risk": "spawns sub-execution whose nested tool calls the gate may never see", "match": ["Agent", "Task", "Workflow", "Skill", "TaskCreate"], "paths": null, "shell": null, "action": "deny", "on_autonomous": null, "approval_scope": null, "approval_ttl_secs": null}, {"risk": null, "match": ["Edit", "Write", "MultiEdit", "NotebookEdit"], "paths": {"deny": ["**/.env", "**/.env.*", "**/.git/config", "**/.git/hooks/**"], "allow": ["/workspace/**"]}, "shell": null, "action": "allow", "on_autonomous": null, "approval_scope": null, "approval_ttl_secs": null}, {"risk": null, "match": ["Bash", "BashOutput", "KillShell"], "paths": null, "shell": {"deny_regex": ["rm\\s+(-[a-z]+\\s+)*-[a-z]*r[a-z]*(\\s+-[a-z]+)*\\s+/\\*?(\\s|$)", "\\bcurl\\b", "\\bwget\\b", "\\bnc\\b", "\\bssh\\b", "\\bscp\\b", "git\\s+push\\b.*\\s(--force(-with-lease)?|-f)\\b", "\\bsudo\\b", "/etc/passwd", "\\bchmod\\s+777\\b"], "on_no_match": "approve", "allow_prefixes": ["ls", "cat", "head", "tail", "wc", "grep", "rg", "find", "pwd", "echo", "which", "env | grep", "python", "python3", "pytest", "pip install -r", "node", "npm test", "npm run test", "npx jest", "npx vitest", "cargo test", "cargo build", "cargo check", "go test", "make test", "git status", "git diff", "git log", "git add", "git commit", "git show", "cd", "mkdir", "touch", "mv", "cp", "sed", "awk", "diff", "sort", "uniq", "cut", "tr", "stat", "file", "du", "printf", "basename", "dirname", "date"]}, "action": "allow", "on_autonomous": null, "approval_scope": null, "approval_ttl_secs": null}, {"risk": "network egress from sandbox", "match": ["WebFetch", "WebSearch", "DesignSync", "Monitor"], "paths": null, "shell": null, "action": "deny", "on_autonomous": null, "approval_scope": null, "approval_ttl_secs": null}, {"risk": "effect outside this run''s disposable workspace", "match": ["TaskStop", "TaskUpdate", "SendMessage", "CronCreate", "CronDelete", "ScheduleWakeup", "PushNotification", "EnterWorktree", "ExitWorktree"], "paths": null, "shell": null, "action": "approve", "on_autonomous": null, "approval_scope": null, "approval_ttl_secs": null}, {"risk": "unreviewed MCP tool", "match": ["mcp__*"], "paths": null, "shell": null, "action": "approve", "on_autonomous": null, "approval_scope": null, "approval_ttl_secs": null}], "egress": {"mode": "proxy-only"}, "budgets": {"max_tokens": 2000000, "max_cost_usd": 5.0, "max_tool_calls": 200, "max_wall_clock_secs": 3600}, "network": {"deny": [], "allow": [], "max_mode": "approved", "max_grant_secs": null, "require_approval": true, "allow_public_with_brokered": false}, "autonomy": {"permitted": true, "on_approval_rule": "deny"}, "defaults": {"tool_action": "approve"}, "approvals": {"scope": "once", "timeout_action": "deny", "default_ttl_secs": 600}}'::jsonb),
    ('governed', '{"name": "governed", "tools": [{"risk": null, "match": ["Read", "Glob", "Grep", "LS", "TodoWrite", "NotebookRead", "EnterPlanMode", "ExitPlanMode", "AskUserQuestion"], "paths": null, "shell": null, "action": "allow", "on_autonomous": null, "approval_scope": null, "approval_ttl_secs": null}, {"risk": "writes require a human under the governed tier", "match": ["Edit", "Write", "MultiEdit", "NotebookEdit"], "paths": {"deny": ["**/.env", "**/.env.*", "**/.git/config", "**/.git/hooks/**"], "allow": ["/workspace/**"]}, "shell": null, "action": "approve", "on_autonomous": null, "approval_scope": null, "approval_ttl_secs": null}, {"risk": null, "match": ["Bash", "BashOutput", "KillShell"], "paths": null, "shell": {"deny_regex": ["\\bcurl\\b", "\\bwget\\b", "\\bnc\\b", "\\bssh\\b", "\\bscp\\b", "\\bsudo\\b", "/etc/passwd"], "on_no_match": "deny", "allow_prefixes": ["ls", "cat", "head", "tail", "wc", "grep", "rg", "find", "pwd", "git status", "git diff", "git log"]}, "action": "allow", "on_autonomous": null, "approval_scope": null, "approval_ttl_secs": null}, {"risk": "unreviewed MCP tool", "match": ["mcp__*"], "paths": null, "shell": null, "action": "approve", "on_autonomous": null, "approval_scope": null, "approval_ttl_secs": null}], "egress": {"mode": "proxy-only"}, "budgets": {"max_tokens": 300000, "max_cost_usd": 1.0, "max_tool_calls": 40, "max_wall_clock_secs": 900}, "autonomy": {"permitted": false, "on_approval_rule": "deny"}, "defaults": {"tool_action": "deny"}, "approvals": {"scope": "once", "timeout_action": "deny", "default_ttl_secs": 300}}'::jsonb)
),
created as (
  insert into policies (id, tenant_id, name)
  select gen_random_uuid(), t.id, tiers.name
    from tenants t cross join tiers
  on conflict (tenant_id, name) do nothing
  returning id, tenant_id, name
)
insert into policy_versions
  (id, tenant_id, policy_id, version, content, yaml_source, summary, author)
select gen_random_uuid(), c.tenant_id, c.id, 1, tiers.content, null,
       'seeded tier: ' || c.name, 'seed'
  from created c join tiers on tiers.name = c.name;
