[package]
name = "fluidbox-cli"
version = "0.4.0-rc.1"
edition.workspace = true
license.workspace = true

[[bin]]
name = "fluidbox"
path = "src/main.rs"

[dependencies]
clap.workspace = true
reqwest.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
futures.workspace = true
dotenvy.workspace = true
